node {
  stage('Checkout') {
    checkout scm
  }

  stage('Test in Docker') {
    script {
      // Define the Docker image
      def img = docker.image('node:16-alpine')

      // Pull the image if not already available
      img.pull()

      // Run commands inside the Docker container
      img.inside(
        // Mount the Windows workspace into /workspace in the container
        '-v C:\\ProgramData\\Jenkins\\.jenkins\\workspace\\Zero-to-hero:/workspace ' +
        // Set the working directory inside the container
        '-w /workspace'
      ) {
        // Execute the desired command
        bat 'node --version'
      }
    }
  }
}
