pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker {
          image 'maven:3.8.1-adoptopenjdk-11'
          args '-v C:\\ProgramData\\Jenkins\\.jenkins\\workspace\\my-first-pipleline:/workspace -w /workspace'
        }
      }
      steps {
        bat 'mvn --version'
      }
    }
    stage('Front-end') {
      agent {
        docker {
          image 'node:16-alpine'
          args '-v C:\\ProgramData\\Jenkins\\.jenkins\\workspace\\my-first-pipleline:/workspace -w /workspace'
        }
      }
      steps {
        bat 'node --version'
      }
    }
  }
}
