pipeline {
  agent any

  stages {
    stage('Back-end') {
      steps {
        bat """
          docker pull maven:3.8.1-adoptopenjdk-11
          docker run --rm ^
            -v C:\\ProgramData\\Jenkins\\.jenkins\\workspace\\my-first-pipleline:/workspace ^
            -w /workspace ^
            maven:3.8.1-adoptopenjdk-11 ^
            mvn --version
        """
      }
    }

    stage('Front-end') {
      steps {
        bat """
          docker pull node:16-alpine
          docker run --rm ^
            -v C:\\ProgramData\\Jenkins\\.jenkins\\workspace\\my-first-pipleline:/workspace ^
            -w /workspace ^
            node:16-alpine ^
            node --version
        """
      }
    }
  }
}
